# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcharts', '0002_remove_vaxcoverage_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaxChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=200)),
            ],
        ),
    ]
