# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcharts', '0003_vaxchoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VaxIncidenceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('disease', models.CharField(max_length=200)),
                ('vaccine', models.CharField(max_length=200)),
                ('incidence_rate', models.FloatField()),
            ],
        ),
    ]
